services:
  app:
    build: ./project-mesim
    container_name: project-mesim
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - alpha_network

networks:
  alpha_network:
    external: true
